FROM okwrtdsh/anaconda3:9.2-cudnn7

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/davinnovation/ppgnet_docker

WORKDIR ppgnet_docker

RUN conda create -f ppgnet.yml -n ppgnet
RUN conda activate ppgnet

RUN sh ppgnet_train.sh
